-- =======================================================
-- Create: 28.08.2023. А.Никитин
-- Description:	DWH-2195 Заполнение таблицы marketing.docredy_pts_uat
-- =======================================================
CREATE PROC [marketing].[fill_docredy_pts_uat]
	@CMRClientGUID nvarchar(36) = null
AS
BEGIN
	BEGIN TRY
		IF NOT EXISTS(SELECT TOP(1) 1 FROM risk.docredy_buffer)
		BEGIN
			;THROW 51000, 'Отсутствуют данные в risk.docredy_buffer', 16
		END
        

		BEGIN TRAN
			truncate table marketing.docredy_pts_uat
		
			INSERT marketing.docredy_pts_uat
			(
				marketProposal_ID,
				cdate,
				dwh_created_at,
				RequestСсылка,
				RequestGUID,
				external_id,
				category,
				Type,
				main_limit,
				[Минимальный срок кредитования],
				[Ставка %],
				[Сумма платежа],
				[Рекомендуемая дата повторного обращения],
				fio,
				birth_date,
				--Auto,
				vin,
				--pos,
				--rp,
				channel,
				doc_ser,
				doc_num,
				ТелефонМобильный,
				region_projivaniya,
				Berem_pts,
				Nalichie_pts,
				--not_end,
				--flag_good,
				--max_dpd_all,
				--max_dpd_now,
				--overdue_days,
				--dod,
				num_active_days,
				market_price,
				collateral_id,
				price_date,
				discount_price,
				col_rest,
				pers_rest,
				koeff,
				--num_closed,
				limit_car,
				limit_client,
				--red_visa,
				--red_dod,
				--red_dpd,
				--red_limit,
				--is_red,
				--is_green,
				--is_yellow,
				--score,
				--score_date,
				--has_bureau,
				--scoring,
				--[group],
				--GUID,
				--brand,
				--model,
				--year,
				--max_delta_active,
				--max_dpd_da,
				--RED_CAR,
				--RED_CHD,
				--is_orange,
				--red_velocity,
				--red_pmt_delay,
				CRMClientGUID,
				
				last_name,
				first_name,
				patronymic,
				market_proposal_category_id,
				market_proposal_category_name,
				market_proposal_category_code,
				market_proposal_type_id,
				market_proposal_type_name,
				market_proposal_type_code,
				phone,
				client_email,
				passportNotValid,
				lkUserId,
				phoneInBlackList,
				clientTimeZone,
				ТранспортноеСредствоGuid,
				ТранспортноеСредствоНаименование,
				МаркаGuid,
				МодельGuid,
				РегистрационныйНомер,
				ТранспортноеСредствоГод,
				МаркаПТС,
				МодельПТС,
				СерияПТС,
				НомерПТС,
				lead_Id,
				[product_type_id],
				[product_type_name],
				[product_type_code]
			)
			SELECT
				D.marketProposal_ID,
				D.cdate,
				D.dwh_created_at,
				D.RequestСсылка,
				D.RequestGUID,
				D.external_id,
				D.category,
				D.Type,
				D.main_limit,
				D.[Минимальный срок кредитования],
				D.[Ставка %],
				D.[Сумма платежа],
				D.[Рекомендуемая дата повторного обращения],
				D.fio,
				D.birth_date,
				--D.Auto,
				D.vin,
				--D.pos,
				--D.rp,
				D.channel,
				D.doc_ser,
				D.doc_num,
				D.ТелефонМобильный,
				D.region_projivaniya,
				D.Berem_pts,
				D.Nalichie_pts,
				--D.not_end,
				--D.flag_good,
				--D.max_dpd_all,
				--D.max_dpd_now,
				--D.overdue_days,
				--D.dod,
				D.num_active_days,
				D.market_price,
				D.collateral_id,
				D.price_date,
				D.discount_price,
				D.col_rest,
				D.pers_rest,
				D.koeff,
				--D.num_closed,
				D.limit_car,
				D.limit_client,
				--D.red_visa,
				--D.red_dod,
				--D.red_dpd,
				--D.red_limit,
				--D.is_red,
				--D.is_green,
				--D.is_yellow,
				--D.score,
				--D.score_date,
				--D.has_bureau,
				--D.scoring,
				--D.[group],
				--D.GUID,
				--D.brand,
				--D.model,
				--D.year,
				--D.max_delta_active,
				--D.max_dpd_da,
				--D.RED_CAR,
				--D.RED_CHD,
				--D.is_orange,
				--D.red_velocity,
				--D.red_pmt_delay,
				D.CRMClientGUID,
				D.last_name,
				D.first_name,
				D.patronymic,
				D.market_proposal_category_id,
				D.market_proposal_category_name,
				D.market_proposal_category_code,
				D.market_proposal_type_id,
				D.market_proposal_type_name,
				D.market_proposal_type_code,
				D.phone,
				D.client_email,
				D.passportNotValid,
				D.lkUserId,
				D.phoneInBlackList,
				D.clientTimeZone,
				D.ТранспортноеСредствоGuid,
				D.ТранспортноеСредствоНаименование,
				D.МаркаGuid,
				D.МодельGuid,
				D.РегистрационныйНомер,
				D.ТранспортноеСредствоГод,
				D.МаркаПТС,
				D.МодельПТС,
				D.СерияПТС,
				D.НомерПТС,
				lead_Id,
				[product_type_id],
				[product_type_name],
				[product_type_code]
			FROM marketing.docredy_pts AS D
			WHERE D.cdate = cast(getdate() as date)
				AND exists(
					SELECT top(1) 1 
					FROM Stg._1cCRM.Документ_ЗаявкаНаЗаймПодПТС_uat AS uat
					WHERE uat.Номер = D.external_id
				)
				AND (D.CRMClientGUID = @CMRClientGUID or @CMRClientGUID is null)

		COMMIT TRAN

	end try
	begin catch
		if @@TRANCOUNT>0
			rollback tran
		;throw
	end catch
end
