-- exec [Create_dm_ConstructorCollection]
CREATE   PROC dbo.Create_dm_ConstructorJudicialClaims
as

begin

set nocount on
SET XACT_ABORT ON

--drop table if exists dbo.dm_ConstructorJudicialClaims
TRUNCATE TABLE dbo.dm_ConstructorJudicialClaims

INSERT dbo.dm_ConstructorJudicialClaims
(
    Id,
    UpdatedBy,
    CreatedBy,
    CreateDate,
    UpdateDate,
    ClaimInCourtDate,
    AmountRequirements,
    NumberCasesInCourt,
    ViewOfCourtsDecision,
    ResultOfCourtsDecision,
    JudgmentDate,
    AmountJudgment,
    ReceiptOfJudgmentDate,
    PrincipalDebtOnClaim,
    PercentageOnClaim,
    PenaltiesOnClaim,
    StateDutyOnClaim,
    PrincipalDebtOnJudgment,
    PercentageOnJudgment,
    PenaltiesOnJudgment,
    StateDutyOnJudgment,
    Comment,
    ClaimRevocationReasonId,
    AdoptionProductionDate,
    AppealResult,
    Appellant,
    ClaimJPForm,
    ClaimRevocationDate,
    CourtClaimSendingDate,
    CourtDate,
    DebtClaimSendingDate,
    EdgeEmergenceNotificationDate,
    FeedWay,
    JudgmentEntryIntoForceDate,
    ManualFeed,
    MonitoringResult,
    NextAction,
    OtherClaims,
    OtherClaimsJudgment,
    OutgoingCourtClaimNumber,
    OutgoingDebtClaimNumber,
    PledgeNotificationNumber,
    RegistryDebtClaimNumber,
    ResultCourtsComment,
    ReturnReasonId,
    TaxSendingDate,
    JudicialProceedingId,
    DocumentGuid,
    CourtClaimSendingRegistryNumber,
    InterimMeasuresComment,
    OrderRequestSendingData,
    StateDutyPaymentRequestDate,
    StateDutyPaymentRequestNumber,
    StateDutyPaymentRequestStatusId,
    InterimMeasuresDate,
    DWHInsertedDate,
    ProcessGUID
)
Select 
	Id,
    UpdatedBy,
    CreatedBy,
    CreateDate,
    UpdateDate,
    ClaimInCourtDate,
    AmountRequirements,
    NumberCasesInCourt,
    ViewOfCourtsDecision,
    ResultOfCourtsDecision,
    JudgmentDate,
    AmountJudgment,
    ReceiptOfJudgmentDate,
    PrincipalDebtOnClaim,
    PercentageOnClaim,
    PenaltiesOnClaim,
    StateDutyOnClaim,
    PrincipalDebtOnJudgment,
    PercentageOnJudgment,
    PenaltiesOnJudgment,
    StateDutyOnJudgment,
    Comment,
    ClaimRevocationReasonId,
    AdoptionProductionDate,
    AppealResult,
    Appellant,
    ClaimJPForm,
    ClaimRevocationDate,
    CourtClaimSendingDate,
    CourtDate,
    DebtClaimSendingDate,
    EdgeEmergenceNotificationDate,
    FeedWay,
    JudgmentEntryIntoForceDate,
    ManualFeed,
    MonitoringResult,
    NextAction,
    OtherClaims,
    OtherClaimsJudgment,
    OutgoingCourtClaimNumber,
    OutgoingDebtClaimNumber,
    PledgeNotificationNumber,
    RegistryDebtClaimNumber,
    ResultCourtsComment,
    ReturnReasonId,
    TaxSendingDate,
    JudicialProceedingId,
    DocumentGuid,
    CourtClaimSendingRegistryNumber,
    InterimMeasuresComment,
    OrderRequestSendingData,
    StateDutyPaymentRequestDate,
    StateDutyPaymentRequestNumber,
    StateDutyPaymentRequestStatusId,
    InterimMeasuresDate,
    DWHInsertedDate,
    ProcessGUID
--into dbo.dm_ConstructorJudicialClaims
from [Stg]._Collection.JudicialClaims

end
