CREATE   PROC dbo.Create_dm_ConstructorCustomers
as

begin

set nocount on
SET XACT_ABORT ON



--select top 100 * from dbo.dm_ConstructorCollection
--drop table if exists dbo.dm_ConstructorCustomers
TRUNCATE TABLE dbo.dm_ConstructorCustomers

INSERT dbo.dm_ConstructorCustomers
(
    Id,
    ФИО,
    [Количество дней просрочки],
    [Кол-во нарушенных обещаний],
    IdCollectingAgencyState,
    IdCollectingStage,
    [Количество активных займов],
    CrmCustomerId,
    IdCustomerType,
    MobilePhone,
    CurrentNonPaymentReasonId,
    HasAnyDayOfDelay,
    StatusNameList,
    [Сумма просрочки на текущую дату полная],
    [Сумма просрочки на текущую дату],
    [Дата последней коммуникации по клиенту],
    [Дата последнего платежа],
    [Количество активных договоров],
    StatusOfSubprocessId,
    HasReduceTwentyPercentInterestRate,
    [Сумма последнего платежа],
    OutReserves,
    [Соглашение об ЭДО],
    NumberOfActiveEnforcementProceeding,
    CollectingStageReasonTransitionId,
    NeedStartProcessFraudProceeding,
    [Ответственный взыскатель],
    [Куратор СП],
    [Куратор по реализации],
    [Куратор ИП],
    [Полных лет],
    Гражданство,
    Пол,
    [Место рождения],
    Series,
    [Серия Номер Паспорта],
    [Дата выдачи],
    [Кем выдан паспорт],
    [Код подразделения],
    Email,
    [Дата рождения],
    [Семейное положение],
    [Стадия коллектинга клиента],
    [Регион постоянной регистрации],
    [Регион фактического проживания],
    [Дата регистрации],
    [Проживает с],
    [Адрес постоянной регистрации],
    [Адрес фактического проживания],
    [Домашний телефон],
    IdCustomer,
    Должность,
    [Стаж (год)],
    [Стаж (месяцев)],
    Зарплата,
    [Тип занятости],
    [Отрасль занятости],
    [Адрес организации],
    [ФИО руководителя],
    [Телефон руководителя],
    [Среднемесячный доход],
    [Доход супруга(и)],
    [Обязательные расходы заемщика и супруга],
    [Имя клиента в МП],
    [Логин клиента в МП],
    [Последняя активность клиента]
)
Select 
	Id,
    ФИО,
    [Количество дней просрочки],
    [Кол-во нарушенных обещаний],
    IdCollectingAgencyState,
    IdCollectingStage,
    [Количество активных займов],
    CrmCustomerId,
    IdCustomerType,
    MobilePhone,
    CurrentNonPaymentReasonId,
    HasAnyDayOfDelay,
    StatusNameList,
    [Сумма просрочки на текущую дату полная],
    [Сумма просрочки на текущую дату],
    [Дата последней коммуникации по клиенту],
    [Дата последнего платежа],
    [Количество активных договоров],
    StatusOfSubprocessId,
    HasReduceTwentyPercentInterestRate,
    [Сумма последнего платежа],
    OutReserves,
    [Соглашение об ЭДО],
    NumberOfActiveEnforcementProceeding,
    CollectingStageReasonTransitionId,
    NeedStartProcessFraudProceeding,
    [Ответственный взыскатель],
    [Куратор СП],
    [Куратор по реализации],
    [Куратор ИП],
    [Полных лет],
    Гражданство,
    Пол,
    [Место рождения],
    Series,
    [Серия Номер Паспорта],
    [Дата выдачи],
    [Кем выдан паспорт],
    [Код подразделения],
    Email,
    [Дата рождения],
    [Семейное положение],
    [Стадия коллектинга клиента],
    [Регион постоянной регистрации],
    [Регион фактического проживания],
    [Дата регистрации],
    [Проживает с],
    [Адрес постоянной регистрации],
    [Адрес фактического проживания],
    [Домашний телефон],
    IdCustomer,
    Должность,
    [Стаж (год)],
    [Стаж (месяцев)],
    Зарплата,
    [Тип занятости],
    [Отрасль занятости],
    [Адрес организации],
    [ФИО руководителя],
    [Телефон руководителя],
    [Среднемесячный доход],
    [Доход супруга(и)],
    [Обязательные расходы заемщика и супруга],
    [Имя клиента в МП],
    [Логин клиента в МП],
    [Последняя активность клиента] 
--into dbo.dm_ConstructorCustomers
from [dwh2].[cubes].[dim_ConstructorCustomers]


end
